# Generated by Django 5.1.5 on 2026-02-25 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0015_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 2, 53, 39, 896180)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 2, 53, 39, 894680)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 2, 53, 39, 895431)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 2, 53, 39, 893929)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 2, 53, 39, 893179)),
        ),
    ]
